#+TITLE: Leon Lan
#+OPTIONS: toc:nil

Hey, I'm Leon!
I'm a fourth-year PhD candidate in Operations Research at VU Amsterdam.
My work focuses on machine scheduling and vehicle routing problems motivated by industrial applications.
I like to solve large-scale and dynamic problems using simple methods and easy-to-use software.

@@html:<a href='mailto:l.lan@vu.nl'><i class="fa fa-envelope" style="font-size:20px"></i></a>@@  |  @@html:<a href='https://www.linkedin.com/in/leonlan/'><i class="fa fa-linkedin" style="font-size:20px"></i></a>@@  | @@html:<a href='https://github.com/leonlan'><i class="fa fa-github" style="font-size:20px"></i></a>@@ | @@html:<a href='https://scholar.google.com/citations?user=2yM55FwAAAAJ&hl=en'><i class="fa fa-graduation-cap" style="font-size:20px"></i></a>@@



@@html:<h4>Published papers</h4>@@


1. Bekker, R., Bharti, B., *Lan, L.*, & Mandjes, M. (2024). A queueing-based approach for integrated routing and appointment scheduling. European Journal of Operations Research.
   [[https://www.sciencedirect.com/science/article/pii/S0377221724003977?via%3Dihub][paper]] | [[https://github.com/leonlan/routing-appointment-scheduling][github]].
2. *Lan, L.*, van Doorn, J., Wouda, N. A., Rijal, A., & Bhulai, S. (2024). An iterative sample scenario approach for the dynamic dispatch waves problem. Transportation Science.
   [[https://pubsonline.informs.org/doi/10.1287/trsc.2023.0111][paper]] | [[https://arxiv.org/abs/2308.14476][arXiv]] | [[https://github.com/leonlan/dynamic-dispatch-waves][github]].
3. Wouda, N. A., *Lan, L.*, & Kool, W. (2024). PyVRP: a high-performance VRP solver package. INFORMS Journal on Computing.
   [[https://doi.org/10.1287/ijoc.2023.0055][paper]]  | [[https://arxiv.org/abs/2403.13795][arXiv]] | [[https://github.com/PyVRP/PyVRP][github]].
4. Wouda, N. A., & *Lan, L*. (2023). ALNS: A Python implementation of the adaptive large neighbourhood search metaheuristic. Journal of Open Source Software.
   [[https://joss.theoj.org/papers/10.21105/joss.05028][paper]] | [[https://github.com/N-Wouda/ALNS][github]].

@@html:<h4>Submitted papers</h4>@@

1. *Lan, L*., & Zocca, A. (2023). Mixed-integer linear programming approaches for tree partitioning of power networks.
   [[https://doi.org/10.48550/arXiv.2110.07000][arXiv]] | [[https://github.com/leonlan/tree-partitioning][github]].

@@html:<h4>Work in progress</h4>@@

1. *Lan, L*., & Berkhout, J. (2024). PyJobShop: Solving scheduling problems with constraint programming in Python.
   [[https://github.com/PyJobShop/PyJobShop][github]].
2. *Lan, L*., & Berkhout, J., & van der Mei, R. (2024). Make-to-order scheduling in the animal feed manufacturing industry.


@@html:<h4>Software</h4>@@

1. *[[https://github.com/PyVRP/pyvrp][PyVRP]]*: An open-source, state-of-the-art vehicle routing problem solver.
2. *[[https://github.com/leonlan/VRPLIB][VRPLIB]]*: Python library to read and write vehicle routing problem instances.
3. *[[https://github.com/leonlan/pyjobshop][PyJobShop]]*: Solving scheduling problems with constraint programming in Python.
4. *[[https://github.com/N-Wouda/ALNS][ALNS]]*: Python implementation of the adaptive large neighborhood search (ALNS) metaheuristic.
5. *[[https://tour-du-mont-blanc.streamlit.app/][Tour Du Mont Blanc]]*: Availability calendar of huts for the Tour du Mont Blanc hike.


@@html:</section>@@
